name: cd

on: 
    workflow_call: 

jobs: 
     cd:
       runs-on: self-hosted
       steps:

          - name: login
            uses: docker/login-action@v4

            with:
              username: ${{ vars.DOCKER_HUB_USER }}
              password: ${{ secrets.DOCKERHUB_TOKEN }}

          - name: cd
            run: docker compose up -d    