name: ci

on: 
  push:

jobs:
   lint-and-test:
     uses: ./.github/workflows/lint.yml

   build-and-push: 
     secrets: inherit
     needs: lint-and-test
     uses: ./.github/workflows/docker.yml

   deploy: 
      secrets: inherit
      needs: build-and-push
      uses: ./.github/workflows/cd.yml  
  
  
  
