name: ci/cd 
on: 
  push:
    branches: [main]

jobs:
  code:
     runs-on: ubuntu-latest
     steps: 
       - name: copy the code
         run: echo "code cloned"
  build:
     runs-on: ubuntu-latest
     needs: code
     steps:
       - name: build
         run: echo "image is build"
  test:
      runs-on: ubuntu-latest
      needs: build
      steps:
        - name: test the build 
          run: echo "testing is done "
  deploye:
      runs-on: ubuntu-latest
      needs: test
      steps:
        - name: deploy the app
          run:  echo "deployed on server"
   
   
