name: ci/cd 
on: 
  push:
    branches: [main]

jobs:
  code:
     runs-on: ubuntu-latest
     steps:
       - name: copy the code
         run: 
  build:
     runs-on: ubuntu-latest
     steps:
       - name: build
         run: 
  test:
      runs-on: ubuntu-latest
      steps:
        - name: test the build 
          run: 
  deploye:
      runs-on: ubuntu-latest
      steps:
        - name: deploy the app
          run: 
   
   
