# start with workflow name 
name: hellow
# when it should run
on:
 workflow_dispatch: 

jobs:
 # job name  
  greet:
   # where it should run 
   runs-on: ubuntu-latest
   steps:
    - name: say hello
      run: echo "hellow dosto the friest job runs secussesfully"
  buy:
    needs: reponame
    runs-on: ubuntu-latest
    steps:
      - name: say buy
        run: echo "buy buy"
  reponame:
     needs: greet
     runs-on: ubuntu-latest
     steps:
       - name: reponame
         run: echo "repo name is ${{ github.event.repository.name }}"
