name: lint
on: 
 push:

jobs:
    code-lint:
        runs-on: ubuntu-latest
        steps:
           - name: code-copy
             uses: actions/checkout@v7
           
           - name: code -linting 
             run: ruff check .  


